### ISSUE TITLE
Error when migrating using ActiveRecord

### ISSUE THREAD

**Issue by bartroff** [dkuk/a_common_libs#5]
Hi there,

I am getting an error when trying to migrate/install latest version (tried master/development branch as well). I am using MS SQL 2008 via ActiveRecord and Linux Redhat frontend for Redmine 3.3.2

Command: `# rake redmine:plugins:migrate RAILS_ENV=production`

Output:

```
/usr/local/rvm/gems/ruby-2.3.3/gems/tiny_tds-1.3.0/lib/tiny_tds/client.rb:53: warning: TinyTds: :use_utf16 option not supported in this version of FreeTDS.

svn: warning: cannot set LC_CTYPE locale
svn: warning: environment variable LC_CTYPE is UTF-8
svn: warning: please check that your locale name is correct
rake aborted!
NoMethodError: undefined method `<<' for nil:NilClass
/var/www/redmine_prod/plugins/a_common_libs/lib/rmp_sql_ext.rb:256:in `visit_Arel_Attributes_Attribute'
/usr/local/rvm/gems/ruby-2.3.3/gems/arel-5.0.1.20140414130214/lib/arel/visitors/visitor.rb:22:in `visit'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/arel/visitors/sqlserver.rb:147:in `block in visit_Arel_Nodes_SelectStatementWithOutOffset'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/arel/visitors/sqlserver.rb:146:in `map'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/arel/visitors/sqlserver.rb:146:in `visit_Arel_Nodes_SelectStatementWithOutOffset'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-sqlserver-adapter-4.1.6/lib/arel/visitors/sqlserver.rb:15:in `visit_Arel_Nodes_SelectStatement'
/usr/local/rvm/gems/ruby-2.3.3/gems/arel-5.0.1.20140414130214/lib/arel/visitors/visitor.rb:22:in `visit'
/usr/local/rvm/gems/ruby-2.3.3/gems/arel-5.0.1.20140414130214/lib/arel/visitors/visitor.rb:5:in `accept'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:13:in `to_sql'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/querying.rb:39:in `find_by_sql'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/relation.rb:604:in `exec_queries'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/relation.rb:486:in `load'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/relation.rb:231:in `to_a'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/relation/finder_methods.rb:467:in `find_nth_with_limit'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/relation/finder_methods.rb:459:in `find_nth'
/usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-4.1.2/lib/active_record/relation/finder_methods.rb:132:in `first'
/var/www/redmine_prod/app/models/setting.rb:285:in `find_or_default'
/var/www/redmine_prod/app/models/setting.rb:110:in `[]'
/var/www/redmine_prod/app/models/setting.rb:243:in `plugin_a_common_libs'
/var/www/redmine_prod/plugins/a_common_libs/init.rb:134:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/lazy_load_hooks.rb:44:in `each'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/application/finisher.rb:64:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/application.rb:300:in `initialize!'
/var/www/redmine_prod/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `block in require'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:232:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
/var/www/redmine_prod/plugins/a_common_libs/lib/tasks/a_common_libs.rake:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:241:in `load'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:241:in `block in load'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:232:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:241:in `load'
/var/www/redmine_prod/lib/tasks/redmine.rake:186:in `block in <top (required)>'
/var/www/redmine_prod/lib/tasks/redmine.rake:186:in `each'
/var/www/redmine_prod/lib/tasks/redmine.rake:186:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:241:in `load'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:241:in `block in load'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:232:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:241:in `load'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/engine.rb:654:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/engine.rb:654:in `each'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/engine.rb:654:in `run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/application.rb:374:in `run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/engine.rb:449:in `load_tasks'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/railtie.rb:194:in `public_send'
/usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/railtie.rb:194:in `method_missing'
/var/www/redmine_prod/Rakefile:7:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

```

Any help appreciated.

Regards - Allan

**Comment by SkiF91** [comment]
Hello.
1. our repo now moved to bitbucket - https://bitbucket.org/dkuk/a_common_libs (just for info)
2. as i see, you are using old Arel gem (2014), it's reason of this bug.
...
Anyway, thanks, and I have just fixed this bug. Try to checkout to branch 4.0.0 and pull.

**Comment by bartroff** [comment]
Thanks SkiF91, Works perfectly now.
