### ISSUE TITLE
Error in Redmine 4.1

### ISSUE THREAD

**Issue by koren85** [dkuk/a_common_libs#8]
Error install plugin

```
Installing gems required by plugins...
Your application has set without to "development:test". This will override the global value you are currently setting
Migrating plugins. Please be patient, this could take a while...
rake aborted!
NameError: undefined method `store_translations' for module `Redmine::I18n::Backend::Implementation'
/home/redmine/redmine/plugins/a_common_libs/lib/acl/alias_patch.rb:10:in `alias_method'
/home/redmine/redmine/plugins/a_common_libs/lib/acl/alias_patch.rb:10:in `alias_method_chain'
/home/redmine/redmine/plugins/a_common_libs/lib/acl/i18n_backend_pluralization.rb:7:in `block in included'
/home/redmine/redmine/plugins/a_common_libs/lib/acl/i18n_backend_pluralization.rb:6:in `class_eval'
/home/redmine/redmine/plugins/a_common_libs/lib/acl/i18n_backend_pluralization.rb:6:in `included'
/home/redmine/redmine/plugins/a_common_libs/init.rb:43:in `include'
/home/redmine/redmine/plugins/a_common_libs/init.rb:43:in `<encoded>'
/home/redmine/redmine/plugins/a_common_libs/init.rb:2:in `RGLoader_load'
/home/redmine/redmine/plugins/a_common_libs/init.rb:2:in `<top (required)>'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/home/redmine/redmine/lib/redmine/plugin.rb:181:in `block in load'
/home/redmine/redmine/lib/redmine/plugin.rb:172:in `each'
/home/redmine/redmine/lib/redmine/plugin.rb:172:in `load'
/home/redmine/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `block in load'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/engine.rb:663:in `block in load_config_initializer'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/engine.rb:662:in `load_config_initializer'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `block in <class:Engine>'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `each'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
/home/redmine/redmine/config/environment.rb:16:in `<top (required)>'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require_environment!'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

```

**Comment by Luckyvb** [comment]
i found version 2.5.7
#unless Redmine::I18n::Backend::Implementation.included_modules.include?(Acl::I18nImplementationPatch)
unless ::I18n::Backend::Base.included_modules.include?(Acl::I18nImplementationPatch)
  ::I18n::Backend::Base.send :include, Acl::I18nImplementationPatch
end

and at application helper method chain "avatar"_acl
maybe this patches use for redmine <4 version
